

# Sending velocity commands from ROS 2 to Gazebo
- ros_topic_name: "drone/cmd_vel"
  gz_topic_name: "/drone/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
  lazy: false

- ros_topic_name: "drone/enable"
  gz_topic_name: "/drone/enable"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ
  lazy: false


- ros_topic_name: "odom"
  gz_topic_name: "/model/drone/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/tf"
  gz_topic_name: "/model/drone/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS


- ros_topic_name: "joint_states"
  gz_topic_name: "/world/default/model/drone/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
  lazy: false


# Clock configuration
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  lazy: false

